import { NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

const dbPath = path.join(process.cwd(), 'data', 'db.json');

// Helper to ensure db exists and read it
async function getDb() {
  try {
    const data = await fs.readFile(dbPath, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    // If file doesn't exist or is invalid, return empty db
    return { anime: [] };
  }
}

// Helper to write to db
async function saveDb(data: any) {
  try {
    // Ensure the data directory exists
    await fs.mkdir(path.dirname(dbPath), { recursive: true });
    await fs.writeFile(dbPath, JSON.stringify(data, null, 2), 'utf8');
    return true;
  } catch (error) {
    console.error('Failed to save DB', error);
    return false;
  }
}

export async function GET() {
  const db = await getDb();
  return NextResponse.json(db.anime);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const db = await getDb();

    // basic validation
    if (!body.name) {
      return NextResponse.json({ error: 'Name is required' }, { status: 400 });
    }

    // It is assumed the ID is generated by the client, or we could generate it here.
    // Assuming client provides the ID.
    const newAnime = { ...body };
    if (!newAnime.id) {
      newAnime.id = Date.now().toString() + Math.random().toString(36).substring(2, 9);
    }

    db.anime.push(newAnime);
    await saveDb(db);

    return NextResponse.json(newAnime, { status: 201 });
  } catch (err) {
    return NextResponse.json({ error: 'Failed to process POST' }, { status: 500 });
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const db = await getDb();

    if (!body.id) {
      return NextResponse.json({ error: 'ID is required to update' }, { status: 400 });
    }

    const index = db.anime.findIndex((a: any) => a.id === body.id);
    if (index === -1) {
      return NextResponse.json({ error: 'Anime not found' }, { status: 404 });
    }

    db.anime[index] = { ...db.anime[index], ...body };
    await saveDb(db);

    return NextResponse.json(db.anime[index], { status: 200 });
  } catch (err) {
    return NextResponse.json({ error: 'Failed to process PUT' }, { status: 500 });
  }
}

export async function DELETE(request: Request) {
  try {
    const url = new URL(request.url);
    const id = url.searchParams.get('id');

    if (!id) {
      return NextResponse.json({ error: 'ID parameter is required' }, { status: 400 });
    }

    const db = await getDb();
    const initialLength = db.anime.length;
    db.anime = db.anime.filter((a: any) => a.id !== id);

    if (db.anime.length === initialLength) {
      return NextResponse.json({ error: 'Anime not found' }, { status: 404 });
    }

    await saveDb(db);
    return NextResponse.json({ success: true }, { status: 200 });
  } catch (err) {
    return NextResponse.json({ error: 'Failed to process DELETE' }, { status: 500 });
  }
}
